services:
  postgres:
    image: postgres
    container_name: postgres_prisma
    restart: always
    environment:
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"